---
# Default variables for the monitoring role
monitoring_dir: /opt/monitoring
monitoring_loki_version: "latest"
monitoring_loki_http_port: 3100
monitoring_loki_data_dir: "{{ monitoring_dir }}/loki"
