---
alloy_version: "latest"
alloy_config_dir: /etc/alloy
alloy_data_dir: /var/lib/alloy
# IMPORTANT: must be service DNS name inside Docker network
alloy_loki_url: "http://loki:3100/loki/api/v1/push"
