---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Upgrade system packages
  ansible.builtin.apt:
    upgrade: dist

- name: Install base tools
  ansible.builtin.apt:
    name:
      - git
      - curl
      - wget
      - vim
      - tree
      - jq
    state: present

- name: Set timezone to Amsterdam
  community.general.timezone:
    name: Europe/Amsterdam

- name: Speed up boot by disabling network wait timeout
  ansible.builtin.lineinfile:
    path: /etc/systemd/system/network-online.target.wants/systemd-networkd-wait-online.service
    regexp: '^TimeoutStartSec='
    line: 'TimeoutStartSec=10'
    create: false
  ignore_errors: true
