---
- name: Netplan apply
  ansible.builtin.command: netplan apply
  changed_when: false

- name: Restart ssh
  ansible.builtin.systemd:
    name: ssh
    state: restarted

- name: Update grub
  ansible.builtin.command: update-grub
  changed_when: true
  listen: "update grub"
