---
- name: netplan apply
  ansible.builtin.command: netplan apply
  changed_when: false

- name: restart ssh
  ansible.builtin.systemd:
    name: ssh
    state: restarted

- name: update grub
  ansible.builtin.command: update-grub
  listen: "update grub"