---
- name: Ensure ansible user home directory
  ansible.builtin.file:
    path: /home/{{ target_ansible_user }}
    state: directory
    owner: "{{ target_ansible_user }}"
    group: "{{ target_ansible_user }}"
    mode: "0755"

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: /home/{{ target_ansible_user }}/.ssh
    state: directory
    owner: "{{ target_ansible_user }}"
    group: "{{ target_ansible_user }}"
    mode: "0700"

- name: Copy SSH authorized_keys
  ansible.builtin.copy:
    src: "{{ target_authorized_keys_file | default('/root/.ssh/authorized_keys') }}"
    dest: /home/{{ target_ansible_user }}/.ssh/authorized_keys
    owner: "{{ target_ansible_user }}"
    group: "{{ target_ansible_user }}"
    mode: "0600"
    remote_src: true
  when: target_authorized_keys_file is defined

- name: Ensure sudoers entry
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/{{ target_ansible_user }}
    line: "{{ target_ansible_user }} ALL=(ALL) NOPASSWD:ALL"
    create: true
    mode: "0440"
