---
- name: Install web vulnerable services
  ansible.builtin.apt:
    name:
      - apache2
      - php
      - mysql-server
      - php-mysql
    state: present

- name: Install DVWA
  ansible.builtin.git:
    repo: https://github.com/digininja/DVWA.git
    dest: /var/www/html/dvwa
    force: true

- name: Start Apache
  ansible.builtin.systemd:
    name: apache2
    state: started
    enabled: true

- name: Install Metasploitable-like services
  ansible.builtin.apt:
    name:
      - vsftpd
      - telnetd
      - openssh-server
      - smbclient
    state: present

- name: Start vulnerable services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - vsftpd
    - smbd
  when:
    - ansible_facts.services[item] is defined
  ignore_errors: true
