---
galaxy_info:
  author: k0r4y
  description: Configures a vulnerable target machine for pentesting
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - security
    - pentesting
    - target
    - vulnerable
dependencies: []
