---
- name: Restart nftables
  ansible.builtin.systemd:
    name: nftables
    state: restarted
    daemon_reload: true

- name: Update grub
  ansible.builtin.command: update-grub
  changed_when: true
  listen: "update grub"
